---
- name: install httpd package and basic setup
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: install apache
    yum: name=httpd
  - name: install mod ssl
    yum: name=mod_ssl
  - name: start webserver
    service: name=httpd state=started
  - name: open http port
    firewalld: service=http permanent=true state=enabled
  - name: open https port
    firewalld: service=https permanent=true state=enabled
  - name: open ssh port
    firewalld: service=ssh permanent=true state=enabled
  - name: start firewalld service
    service: name=firewalld state=restarted
  - name: add rewrite lines
    blockinfile:
      path: /etc/httpd/conf/httpd.conf
      block: |
        RewriteEngine On
        RewriteCond %{HTTPS} off
        RewriteRule (.*) https://%{SERVER_NAME}/$1 [R,L]
  - name: add path to HTML
    set_fact: file_path=/var/www/html/index.html
  - set_fact: file_content="<html><head><title>sre challenge</title></head><body>sre challenge</body></html>"
  - name: create the file
    file: path="{{ file_path }}" state=touch
  - name: populate file contents
    copy: content="{{ file_content }}" dest="{{ file_path }}"
